databases:
  - name: fsad-db
    databaseName: fsad_sdp
    plan: free

services:
  - type: web
    name: fsad-backend
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: fsad-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: fsad-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: fsad-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: fsad-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: fsad-db
          property: password
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AUTH_OTP_MAIL_REQUIRED
        value: true
      - key: JPA_SHOW_SQL
        value: false
      - key: LOG_LEVEL
        value: INFO
      - key: APP_LOG_LEVEL
        value: INFO
      - key: CORS_ALLOWED_ORIGINS
        sync: false
